In [1]:
# For loop:- range: list/tuple

# While loop:- based on given conditions

In [8]:
a = [1,2,3,5,6,7]

c = 0
while c<13:
    print(c,a)
    c+=1

0 [1, 2, 3, 5, 6, 7]
1 [1, 2, 3, 5, 6, 7]
2 [1, 2, 3, 5, 6, 7]
3 [1, 2, 3, 5, 6, 7]
4 [1, 2, 3, 5, 6, 7]
5 [1, 2, 3, 5, 6, 7]
6 [1, 2, 3, 5, 6, 7]
7 [1, 2, 3, 5, 6, 7]
8 [1, 2, 3, 5, 6, 7]
9 [1, 2, 3, 5, 6, 7]
10 [1, 2, 3, 5, 6, 7]
11 [1, 2, 3, 5, 6, 7]
12 [1, 2, 3, 5, 6, 7]

In [9]:
print(c)

13

In [11]:
# while loop iterate element

a = [1,12,3,4,54,56,67,43,2,23,3,2]

c = 0

while c<len(a):
    print(a[c])
    c+=1

1
12
3
4
54
56
67
43
2
23
3
2

In [12]:
a = (1,12,3,4,54,56,67,43,2,23,3,2)

c = 0

while c<len(a):
    print(a[c])
    c+=1

1
12
3
4
54
56
67
43
2
23
3
2

In [13]:
a = 'ABCDEFRHJJHVGFFCV'

c = 0

while c<len(a):
    print(a[c])
    c+=1

A
B
C
D
E
F
R
H
J
J
H
V
G
F
F
C
V

In [17]:
table = 5

c = 1
while c<11:
    print(f'{table} x {c} = {table*c}')
    c+=1

5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50

In [18]:
import time

while 2==2:
    print('Hello World')
    time.sleep(1)

Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World

KeyboardInterrupt:

In [19]:
#Time print

In [21]:
print(time.asctime())

Thu Apr 18 12:16:23 2024

In [23]:
while True:
    print(time.asctime())
    time.sleep(1)
    display(clear=True)

Thu Apr 18 12:17:38 2024

KeyboardInterrupt:

In [24]:
# nested while loop

In [32]:
a = 2
b = 1
while a<21:
    
#     b = 1 
    while b<11:
        print(f"{a} x {b} = {a*b}")
        
        b+=1
        
    b-=10
    
    a+=1
    print()

2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20

3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30

4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40

5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50

6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60

7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70

8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80

9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90

10 x 1 = 10
10 x 2 = 20
10 x 3 = 30
10 x 4 = 40
10 x 5 = 50
10 x 6 = 60
10 x 7 = 70
10 x 8 = 80
10 x 9 = 90
10 x 10 = 100

11 x 1 = 11
11 x 2 = 22
11 x 3 = 33
11 x 4 = 44
11 x 5 = 55
11 x 6 = 66
11 x 7 = 77
11 x 8 = 88
11 x 9 = 99
11 x 10 = 110

12 x 1 = 12
12 x 2 = 24
12 x 3 = 36
12 x 4 = 48
12 x 5 = 60
12 x 6 = 72
12 x 7 = 84
12 x 8 = 96
12 x 9 = 108
12 x 10 = 120

13 x 1 = 13
13 x 2 = 26
13 x 3 = 39
13 x 4 = 52
13 x 5 = 65
13 x 6 = 78
13 x 7 = 91
13 x 8 = 104
13 x 9 = 117
13 x 10 = 130

14 x 1 = 14
14 x 2 = 28
14 x 3 = 42
14 x 4 = 56
14 x 5 = 70
14 x 6 = 84
14 x 7 = 98
14 x 8 = 112
14 x 9 = 126
14 x 10 = 140

15 x 1 = 15
15 x 2 = 30
15 x 3 = 45
15 x 4 = 60
15 x 5 = 75
15 x 6 = 90
15 x 7 = 105
15 x 8 = 120
15 x 9 = 135
15 x 10 = 150

16 x 1 = 16
16 x 2 = 32
16 x 3 = 48
16 x 4 = 64
16 x 5 = 80
16 x 6 = 96
16 x 7 = 112
16 x 8 = 128
16 x 9 = 144
16 x 10 = 160

17 x 1 = 17
17 x 2 = 34
17 x 3 = 51
17 x 4 = 68
17 x 5 = 85
17 x 6 = 102
17 x 7 = 119
17 x 8 = 136
17 x 9 = 153
17 x 10 = 170

18 x 1 = 18
18 x 2 = 36
18 x 3 = 54
18 x 4 = 72
18 x 5 = 90
18 x 6 = 108
18 x 7 = 126
18 x 8 = 144
18 x 9 = 162
18 x 10 = 180

19 x 1 = 19
19 x 2 = 38
19 x 3 = 57
19 x 4 = 76
19 x 5 = 95
19 x 6 = 114
19 x 7 = 133
19 x 8 = 152
19 x 9 = 171
19 x 10 = 190

20 x 1 = 20
20 x 2 = 40
20 x 3 = 60
20 x 4 = 80
20 x 5 = 100
20 x 6 = 120
20 x 7 = 140
20 x 8 = 160
20 x 9 = 180
20 x 10 = 200

In [33]:
# break, continue,pass

In [38]:
a = [1,23,4,456,21,33,5457]

c = 0

while c<len(a):
    if a[c]!=21:
        print(a[c],':',a[c]**2)
    else:
        break
    c+=1

1 : 1
23 : 529
4 : 16
456 : 207936

In [39]:
a = [1,23,4,456,21,33,5457]

while True:
    pass

KeyboardInterrupt:

In [40]:
while c<len(a):
    pass
    c+=1

In [41]:
a

[1, 23, 4, 456, 21, 33, 5457]

In [42]:
counter = 0
while counter<len(a):
    if a[counter] == 21:
        pass
    else:
        print(a[counter],':',a[counter]**2)
    counter+=1

1 : 1
23 : 529
4 : 16
456 : 207936
33 : 1089
5457 : 29778849

In [43]:
a

[1, 23, 4, 456, 21, 33, 5457]

In [49]:
counter = 0
while counter<len(a):
    if a[counter] == 21:
        counter+=1
        continue
        
    else:
        print(a[counter],':',a[counter]**2)
    
    counter+=1

1 : 1
23 : 529
4 : 16
456 : 207936

In [51]:
while True:
    break

In [65]:
# common elements

a = [1,2,3,45,5,6,76,78]
b = [4,5,6,7,8,89]

common = []

c = 0
while c<len(a):
    d  = 0
    while d<len(b):
        if a[c] == b[d]:
            common.append(a[c])
        d+=1
    c+=1
    
print(common)

[5, 6]

In [67]:
a = [1,2,3,45,5,6,76,78]
b = [4,5,3,6,7,8,89]
c = [4,5,3,6,7,8,90,0]

common = []



counter1 = 0
while counter1<len(a):
    
    counter2 = 0
    while counter2<len(b):
        
        counter3 = 0
        while counter3<len(c):
            
            if a[counter1] == b[counter2] == c[counter3]:
                
                common.append(a[counter1])
            
            counter3+=1
        
        counter2+=1
    
    counter1+=1
    
print(common)

[3, 5, 6]

# Question

In [3]:
length = 5
char = '*'
for i in range(1,length+1):
    print(i*f'{char} ')
    
# for i in range(length-1,0,-1):
#     print(i*f'{char} ')

*
* *
* * *
* * * *
* * * * *

In [7]:
length = 5

for i in range(1,length+1):
    print(i*f'{char} ')
    
for j in range(length-1,0,-1):
    print(j*f'{char} ')

*
* *
* * *
* * * *
* * * * *
* * * *
* * *
* *
*

In [8]:
# 1
# 1 2
# 1 2 3
# 1 2 3 4
# 1 2 3 4 5

In [13]:
user = 5
for i in range(1,user+1):
    for j in range(1,i+1):
        print(j,end=' ')
    print()

1
1 2
1 2 3
1 2 3 4
1 2 3 4 5

In [14]:
# while else

In [22]:
a = [12,43,53,42,345467]

i = 0
while i<len(a):
    if a[i]!=42:
        print(a[i]+10)
    else:
        break
    i+=1
    
else:
    print('Loop Done!!')

22
53
63

In [23]:
# 
import random

In [24]:
for i in range(10):
    user = int(input('Guess a number b/w(1 to 10): '))
    cmp = random.randint(1,10)

    if user == cmp:
        print('You Won!!')
    else:
        print('You Lose comp Won!!')

Guess a number b/w(1 to 10): 3
You Won!!

In [25]:
while True:
    user = int(input('Guess a number b/w(1 to 10): '))
    cmp = random.randint(1,10)

    if user == cmp:
        print('You Won!!')
    else:
        print('You Lose comp Won!!')

Guess a number b/w(1 to 10): 4
You Lose comp Won!!
Guess a number b/w(1 to 10): 2
You Lose comp Won!!
Guess a number b/w(1 to 10): 1
You Lose comp Won!!
Guess a number b/w(1 to 10): 5
You Lose comp Won!!
Guess a number b/w(1 to 10): 6
You Won!!

KeyboardInterrupt

In [26]:
while True:
    user = input('Guess a number b/w(1 to 10): ').lower()
    
    if user == 'exit':
        break
    else:
        user = int(user)
        cmp = random.randint(1,10)

        if user == cmp:
            print('You Won!!')
        else:
            print('You Lose comp Won!!')

Guess a number b/w(1 to 10): 4
You Lose comp Won!!
Guess a number b/w(1 to 10): exit

In [27]:
# one line while loop

In [30]:
import time
while True:print('Hello');time.sleep(1)

Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello

KeyboardInterrupt:

In [31]:
print('Hello')

Hello

In [74]:
import random
import string


name_random = ['Karan','Ajay','lucky','mohan','ravi']
age_random = [random.randint(10,25) for i in range(5)]
class_random = [random.randint(5,12) for i in range(5)]
sec_random = [random.choice(string.ascii_lowercase) for i in range(5)]
add_random = ['Noida','Delhi','ranchi','Goa','Banglore']




data1 = {'Name':'Ajay','Age':23,'Class':12}
data2 = {'Sec':'A','Address':'Noida'}


no_of_data = 100

for m in data1:
    data1[m] = [data1[m]]
for n in data2:
    data2[n] = [data2[n]]
    
    
for i in range(no_of_data):
    for j in data1:
        ans1 = input(f'Enter your {j}: ').title()
        if j == 'Name':
            if ans1 == '':
                data1[j].append(random.choice(name_random).title())
            else:
                data1[j].append(ans1)
                
        elif j == 'Age':
            if ans1 == '':
                data1[j].append(random.choice(age_random))
            else:
                data1[j].append(ans1)
        
        elif j == 'Class':
            if ans1 == '':
                data1[j].append(random.choice(class_random))
            else:
                data1[j].append(ans1)
                
        else:
            pass
        
    for k in data2:
        ans2 = input(f'Enter your {k}: ')
        
        if k == 'Sec':
            if ans2 == '':
                data2[k].append(random.choice(sec_random).title())
            else:
                data2[k].append(ans2)
                
        elif k == 'Address':
            if ans2 == '':
                data2[k].append(random.choice(add_random).title())
            else:
                data2[k].append(ans2)
        
# print(data1)
# print(data2)

data1.update(data2)
import pandas as pd

table = pd.DataFrame(data1)

table

Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:
Enter your Name:
Enter your Age:
Enter your Class:
Enter your Sec:
Enter your Address:

      Name  Age  Class Sec   Address
0     Ajay   23     12   A     Noida
1     Ajay   25      8   L  Banglore
2     Ajay   18      8   Y     Delhi
3     Ravi   19      6   O     Noida
4     Ravi   18      7   Y     Delhi
..     ...  ...    ...  ..       ...
96   Lucky   20     12   L     Noida
97   Karan   18      6   N  Banglore
98    Ajay   25      8   N     Noida
99    Ravi   19      8   N     Noida
100  Lucky   25     11   Y     Noida

[101 rows x 5 columns]

In [78]:
table.to_csv(r"C:\Users\Lenovo\Desktop\random_students.csv")
print('Done')

Done